- project:
    templates:
      - openstack-specs-jobs
    check:
      jobs:
        - openstack-tox-py37
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-py37
        - openstack-tox-linters
